version: '3.7'

services:
  database:
    image: postgis/postgis
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=getbuckets
      - POSTGRES_HOST_AUTH_METHOD=trust

